site_name: Draymonder Docs
site_author: 'Draymonder'
site_description: '文档记录'
site_url: 'https://draymonders.github.io/'
copyright: Copyright © 2020-2023 Draymonder
 
plugins:
  - search
  # - tags

theme: 
  name: material
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.expand
    # - navigation.sections
    - navigation.instant # 
  language: 'zh'

extra:
  search:
      language: 'zh'
  generator: false
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/draymonders
      - icon: fontawesome/solid/paper-plane
        link: mailto:draymonders@gmail.com

markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
#  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
#  - pymdownx.emoji:  # 表情
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
#  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

nav:
  - 主页: index.md
  - 编码人生: 
    - 中间件: 
      - mysql: 
        - 概览: cs-life/middleware/database/mysql/guide_read.md
        - 日志文件: cs-life/middleware/database/mysql/log.md
        - buffer pool: cs-life/middleware/database/mysql/buffer_pool.md
        - 锁: cs-life/middleware/database/mysql/lock.md
        - 索引: cs-life/middleware/database/mysql/index.md
        - 事务: cs-life/middleware/database/mysql/transcation.md
        - 踩坑: cs-life/middleware/database/mysql/practice.md
      - 缓存:
        - 踩坑: cs-life/middleware/cache/practice.md
    - 基础:
      - 网络:
        - Web/RPC 框架: cs-life/network/framework.md
      - 操作系统:
        - Linux命令: cs-life/os/linux.md 
        - Linux下c/c++开发: cs-life/os/cpp_with_linux.md
      - 经典书籍:
        - 设计数据密集型应用: cs-life/ddia/ddia.md
    - 系统设计:
      - 微服务:
        - 微服务设计: cs-life/system_design/micro_services/micro_services.md
        - DNS & CDN & 异地多活: cs-life/system_design/micro_services/disaster_tolerance.md
        - 日志 & 链路追踪 & 监控: cs-life/system_design/micro_services/service_governance.md
      - 设计原则: cs-life/system_design/principle.md
      - 性能测试平台: cs-life/system_design/sturnus/sturnus.md
      - go im: cs-life/system_design/goim/go_im.md
      - 视频进度设计: cs-life/system_design/history/history.md
      - 评论中台设计: cs-life/system_design/comment/comment.md
      # - lab 6.824 doing: cs-life/design/lab_6.824.md
   
    - 其他: 
      - 开发常用: cs-life/other/tools.md
      - Goland: cs-life/other/goland.md
      - Vim 使用: cs-life/other/vim.md
      - Git 使用: cs-life/other/git.md
   
  - 生活:
    - 年度总结:
      - 2023: enjoy/year/2023.md
      - 2022: enjoy/year/2022.md
      - 2021: enjoy/year//2021.md
    - 视频: 
      - 追剧: enjoy/video/video.md
    - 书籍:
      - 文化苦旅: enjoy/book/文化苦旅.md
      - 明朝那些事儿: enjoy/book/明朝那些事儿.md
      - 人间告白: enjoy/book/人间告白.md
    - 骑行: enjoy/bike/index.md
    - 旅行:
      - 2023国庆: enjoy/travel/2023-national/index.md
      - 2023团建: enjoy/travel/2023-tb/index.md
    