site_name: Draymonder Docs
site_author: 'Draymonder'
site_description: '文档记录'
site_url: 'https://draymonders.github.io/'
copyright: Copyright © 2021 Draymonder
 
plugins:
    - search

theme: 
    # name: readthedocs
    name: material

    # 安装命令 pip install mkdocs-rtd-dropdown
    # name: rtd-dropdown
    highlightjs: true

    # palette:
        # primary: 'Blue'
        # accent: 'Pink'
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
    # font:
    #     text: 'Ubuntu'
    #     code: 'Ubuntu Mono'
    language: 'zh'

extra:
    search:
        language: 'zh'
    generator: false
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/draymonders
        - icon: fontawesome/solid/paper-plane
          link: mailto:draymonders@gmail.com

markdown_extentions:
    - toc:
        permalink: true
    - codehilite:
        guess_lang: true
        linenums: true
    - footnotes
    - meta
    - def_list
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.tilde

nav:
    - 主页: index.md
    - 程序人生: 
        - 数据库: 
          - mysql: 
                - 概览: cs-life/database/mysql/guide_read.md
                - 日志文件: cs-life/database/mysql/log.md
                - buffer pool: cs-life/database/mysql/buffer_pool.md
                - 锁: cs-life/database/mysql/lock.md
                - 索引: cs-life/database/mysql/index.md
                - 事务: cs-life/database/mysql/transcation.md
                - 踩坑: cs-life/database/mysql/practice.md
    #     - 缓存:
    #     - 消息队列:
    #     - 网络:
    # - 数据结构:
    #   - 一致性hash: algorithm/datastruct/consistent_hash.md
    #   - 基数树: algorithm/datastruct/radix_tree.md
    - 工具: 
      - 提效工具: project/tools.md
      - goland: project/goland.md
      - vim使用: project/vim.md
      - linux命令: project/linux.md 
      - lab 6.824 doing: project/lab_6.824.md
      - linux下c/c++开发: project/cpp_with_linux.md
      
    # - 工程实践:
    #   - 灰度控制: design/gray_control.md
    #   - python diff数据脚本: design/diff_script.md
    #   - 设计原则: design/about.md 
    #   - grafana监控: design/grafana.md
    # - 踩坑之路: 
    #   - 数据迁移: solution/db-transfer.md
    #   - 负载高分析: solution/high-load-analysis.md
    #   - 网络故障分析: solution/network-analysis.md
    #   - Redis Timeout: solution/redis-timeout.md
    #   - 多线程循环打印: solution/multi-print.md
    # - 操作系统:
    #   - 基础: cs-base/os/os.md
    # - 网络:
      # - HTTP: cs-base/network/http.md
      # - TCP: cs-base/network/tcp.md
      # - 高性能网络编程: cs-base/network/net-program.md
    - 生活:
      - 年度总结:
        - 2022: enjoy/2022.md
        - 2021: enjoy/2021.md
      - 视频: 
        - 追剧: enjoy/video.md
      - 书籍:
        - 人间告白: enjoy/book/人间告白.md
      