site_name: Draymonder Docs
site_author: 'Draymonder'
site_description: '文档记录'
site_url: 'https://draymonders.github.io/'
copyright: Copyright © 2021 Draymonder

nav:
    - 主页: index.md
    - 操作系统:
      - 基础: os/os.md
      - Linux: os/linux.md
    - 数据库:
      # - MySQL: database/db.md
      - MySQL读书笔记: database/mysql-notes.md
    - 网络:
      # - DNS: network/dns.md
      - HTTP: network/http.md
      - TCP: network/tcp.md
      - 高性能网络编程: network/net-program.md
    - Redis: 
      - 使用场景: middleware/redis/redis.md
      - 简单动态字符串: middleware/redis/code-read/sds.md
      - 哈希表: middleware/redis/code-read/hashtable.md
      - 跳表: middleware/redis/code-read/zskiplist.md
      - 命令处理生命周期: middleware/redis/code-read/server-process.md
      - Redis 事务: middleware/redis/code-read/transactions.md
    - 面试: 
      # - 面试题: interview/interview.md
      - 社招面试: interview/social-interview.md
    - 解决方案: 
      - 负载高分析: solution/high-load-analysis.md
      - 网络故障分析: solution/network-analysis.md
      - Redis Timeout: solution/redis-timeout.md
      - 多线程循环打印: solution/multi-print.md
    
plugins:
    - search

markdown_extentions:
    - admonition
    - toc:
        permalink: true

theme: 
  name: readthedocs

  # 安装命令 pip install mkdocs-rtd-dropdown
  # name: rtd-dropdown
  highlightjs: true