site_name: Draymonder Docs
site_author: 'Draymonder'
site_description: '文档记录'
site_url: 'https://draymonders.github.io/'
copyright: Copyright © 2021 Draymonder
 
plugins:
    - search

theme: 
  # name: readthedocs
  name: material

  # 安装命令 pip install mkdocs-rtd-dropdown
  # name: rtd-dropdown
  # palette:
      # primary: 'Blue'
      # accent: 'Pink'
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
  # font:
  #     text: 'Ubuntu'
  #     code: 'Ubuntu Mono'
  language: 'zh'

extra:
  search:
      language: 'zh'
  generator: false
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/draymonders
      - icon: fontawesome/solid/paper-plane
        link: mailto:draymonders@gmail.com

markdown_extensions:
  - codehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

nav:
  - 主页: index.md
  - 编码人生: 
    - 系统设计:
      - 微服务:
        - 微服务设计: cs-life/system_design/micro_services/micro_services.md
        - DNS & CDN & 异地多活: cs-life/system_design/micro_services/disaster_tolerance.md
        - 日志 & 链路追踪 & 监控: cs-life/system_design/micro_services/service_governance.md
      - 设计原则: cs-life/system_design/principle.md
      - 性能测试平台: cs-life/system_design/sturnus/sturnus.md
      - go im: cs-life/system_design/goim/go_im.md
      - 视频进度设计: cs-life/system_design/history/history.md
      - 评论中台设计: cs-life/system_design/comment/comment.md
      # - lab 6.824 doing: cs-life/design/lab_6.824.md
    - 网络:
      - Web/RPC 框架: cs-life/network/framework.md
    - 操作系统:
      - Linux命令: cs-life/os/linux.md 
      - Linux下c/c++开发: cs-life/os/cpp_with_linux.md
    - 其他: 
      - 开发常用: cs-life/other/tools.md
      - Goland: cs-life/other/goland.md
      - Vim 使用: cs-life/other/vim.md
      - Git 使用: cs-life/other/git.md
    - 数据库: 
      - mysql: 
        - 概览: cs-life/database/mysql/guide_read.md
        - 日志文件: cs-life/database/mysql/log.md
        - buffer pool: cs-life/database/mysql/buffer_pool.md
        - 锁: cs-life/database/mysql/lock.md
        - 索引: cs-life/database/mysql/index.md
        - 事务: cs-life/database/mysql/transcation.md
        - 踩坑: cs-life/database/mysql/practice.md
   
  - 生活:
    - 年度总结:
      - 2022: enjoy/2022.md
      - 2021: enjoy/2021.md
    - 视频: 
      - 追剧: enjoy/video.md
    - 书籍:
      - 人间告白: enjoy/book/人间告白.md
      