site_name: Draymonder Docs
site_author: 'Draymonder'
site_description: '文档记录'
site_url: 'https://draymonders.github.io/'
copyright: Copyright © 2021 Draymonder


nav:
    - Index: index.md
    - Algorithm: algorithm.md
    - Java: java.md
    - Database:
      - Mysql: mysql.md
      - Mongo: mongo.md
    - Middlewares:
      - Kafka: kafka.md
    - Network: network.md
    - Linux: linux.md
    
plugins:
    - search

markdown_extentions:
    - admonition

theme: 
  name: readthedocs
  highlightjs: true