site_name: Draymonder Docs
site_author: 'Draymonder'
site_description: '文档记录'
site_url: 'https://draymonders.github.io/'
copyright: Copyright © 2021 Draymonder


nav:
    - 主页: index.md
    - 算法: algorithm.md
    - Java: java.md
    - 数据库:
      - Mysql: mysql.md
      - Mongo: mongo.md
    - 中间件:
      - Kafka: kafka.md
    - 网络: network.md
    
plugins:
    - search

markdown_extentions:
  - admonition

theme: 
  name: readthedocs
  highlightjs: true