site_name: Draymonder Docs
site_author: 'Draymonder'
site_description: '文档记录'
site_url: 'https://draymonders.github.io/'
copyright: Copyright © 2021 Draymonder

nav:
    - 主页: index.md
    - 碎碎念:
      - 2021: grow-up/2021.md
    - 工程相关: 
      - 效率提升: effective-tools/readme.md
    - 解决方案: 
      - 数据迁移: solution/db-transfer.md
      - 负载高分析: solution/high-load-analysis.md
      - 网络故障分析: solution/network-analysis.md
      - Redis Timeout: solution/redis-timeout.md
      - 多线程循环打印: solution/multi-print.md
    - Redis: 
      - 简单动态字符串: middleware/redis/code-read/sds.md
      - 哈希表: middleware/redis/code-read/hashtable.md
      - 跳表: middleware/redis/code-read/zskiplist.md
      - 命令处理生命周期: middleware/redis/code-read/server-process.md
      - Redis 事务: middleware/redis/code-read/transactions.md
      - 使用场景: middleware/redis/redis.md
      - Redis 集群: middleware/redis/cluster.md
    - 操作系统:
      - 基础: cs-base/os/os.md
      - Linux: cs-base/os/linux.md
    - 数据库:
      # - MySQL: database/db.md
      - MySQL读书笔记: database/mysql-notes.md
    - 网络:
      # - DNS: network/dns.md
      - HTTP: cs-base/network/http.md
      - TCP: cs-base/network/tcp.md
      - 高性能网络编程: cs-base/network/net-program.md
    - 大数据:
      - 成长路线: cs-base/bigdata/grow-up.md
      - 大数据读书笔记: cs-base/bigdata/notes.md
    - 面试: 
      # - 面试题: interview/interview.md
      - 社招面试: interview/social-interview.md
    
plugins:
    - search

markdown_extentions:
    - admonition
    - toc:
        permalink: true

theme: 
  name: readthedocs

  # 安装命令 pip install mkdocs-rtd-dropdown
  # name: rtd-dropdown
  highlightjs: true