site_name: Draymonder Docs
site_author: 'Draymonder'
site_description: '文档记录'
site_url: 'https://draymonders.github.io/'
copyright: Copyright © 2021 Draymonder


nav:
    - Index: index.md
    - Interview: social-interview/index.md
    # - OS:
    #   - os: os/os.md
    # - Java: 
    #   - Collection: java/collection.md
    # - MultiThread:
    #   - MultiThread: java/multi-thread/multi-thread.md
    # - Lock:
    #   - Lock: java/multi-thread/lock.md
    #   - Synchronized: java/multi-thread/synchronized.md
    #   - ReentrantLock: java/multi-thread/reentrantlock.md
    #   - Exception: java/exception.md
    #   - MultiThread: java/multi-thread.md
    # - Middlewares:
    #   - Kafka: middleware/kafka.md
    #   - Mysql: middleware/mysql.md
    #   - Mongo: middleware/mongo.md
    # - Network:
    #   - Network: network/network.md
    # - Linux: linux.md
    # - Algorithm: 
    #   - Algorithm: algorithm/algorithm.md
    
plugins:
    - search

markdown_extentions:
    - admonition

theme: 
  name: readthedocs
  highlightjs: true