site_name: Draymonder Docs
site_author: 'Draymonder'
site_description: '文档记录'
site_url: 'https://draymonders.github.io/'
copyright: Copyright © 2021 Draymonder
 
plugins:
    - search

theme: 
    # name: readthedocs
    name: material

    # 安装命令 pip install mkdocs-rtd-dropdown
    # name: rtd-dropdown
    highlightjs: true

    palette:
        primary: 'Blue'
        accent: 'Pink'
    feature:
        tabs: true
    #font:
        #text: 'Ubuntu'
        #code: 'Ubuntu Mono'
    language: 'zh'

extra:
    search:
        language: 'jp'

markdown_extentions:
    - admonition
    - toc:
        permalink: true
    - codehilite:
        guess_lang: false
        linenums: false

markdown_extentions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
    - 主页: index.md
    # - 碎碎念:
    #   - 2021: grow-up/2021.md
    - 工程相关: 
      - 常用工具: project/tools.md
      - Linux下C/C++开发: project/cpp_with_linux.md
      - Linux命令: project/linux.md 
    - Redis: 
      - 简单动态字符串: middleware/redis/code-read/sds.md
      - 哈希表: middleware/redis/code-read/hashtable.md
      - 跳表: middleware/redis/code-read/zskiplist.md
      - 命令处理生命周期: middleware/redis/code-read/server-process.md
      - Redis 事务: middleware/redis/code-read/transactions.md
      - 使用场景: middleware/redis/redis.md
      - Redis 集群: middleware/redis/cluster.md
    - 解决方案: 
      - 数据迁移: solution/db-transfer.md
      - 负载高分析: solution/high-load-analysis.md
      - 网络故障分析: solution/network-analysis.md
      - Redis Timeout: solution/redis-timeout.md
      - 多线程循环打印: solution/multi-print.md
    - 操作系统:
      - 基础: cs-base/os/os.md
      
    # - 数据库:
      # - MySQL: database/db.md
      # - MySQL读书笔记: database/mysql-notes.md
    - 网络:
      # - DNS: network/dns.md
      - HTTP: cs-base/network/http.md
      - TCP: cs-base/network/tcp.md
      - 高性能网络编程: cs-base/network/net-program.md
    - 面试: 
      # - 面试题: interview/interview.md
      - 社招面试: interview/social-interview.md
    # - 大数据:
    #   - 成长路线: cs-base/bigdata/grow-up.md
    #   - 大数据读书笔记: cs-base/bigdata/notes.md